### PR TITLE
Added "copy, paste, select all, cut, undo" to Desktop Version

### PR DESCRIPTION
**Pull request by puskuruk**
DeepinScreenshot_select-area_20200327001555

### CODE REVIEW

**Comment by seveibar** [comment]
I think we should put Copy, Paste, Select All, Cut Undo under the "Edit" menu (which we may need to create). I think that's where they usually are?

**Comment by puskuruk** [comment]
Yeap that's a good idea! It's coming!

**Comment by puskuruk** [comment]
DeepinScreenshot_select-area_20200327002607

**Comment by seveibar** [comment]
fixes #33

**Pull request merged**
