### PR TITLE
Add nl translation

### PR DESCRIPTION
**Pull request by rickstaa**
I added a Dutch translation to the i18n database. Further, I translated the "Create a Training Course" text in all languages.

### CODE REVIEW

**Comment by seveibar** [comment]
Wow thanks @rickstaa!! This looks great!

**Comment by seveibar** [comment]
@all-contributors add @rickstaa for translations and code

**Review by seveibar — APPROVED** [review]

**Comment by seveibar** [comment]
@rickstaa how do you get all these commit emojis?

**Comment by rickstaa** [comment]
The emotions I use for my commits are (automatically added) by a very useful command-line interface that comes with the [gitmoji project](https://gitmoji.carloscuesta.me/). It is still work in progress so new emotions might be added and deleted to increase readability but I think they already did a great job in making commits better distinguishable.

No problem be sure to tag me if the dutch translation needs an update!

**Comment by rickstaa** [comment]
Also, feel free to tag me if the Dutch translation ever needs an update in the future

**Pull request merged**
