### PR TITLE
Feature/internalization

### PR DESCRIPTION
**Pull request by puskuruk**

### CODE REVIEW

**Comment by puskuruk** [comment]
Yayyyy! I love conflicts :tada: :smile:

**Comment by seveibar** [comment]
@puskuruk I think you mentioned you fixed 6 of the 7 broken tests? Do you want to commit and reassign?

**Comment by seveibar** [comment]
@puskuruk I might not have time to fix these tests. Let's solve it this week.

**Comment by seveibar** [comment]
I had to do some aggressive rebasing to remove a refactoring that I originally recommended. Check out #215

**Pull request closed without merging**
