### PR TITLE
Adds singularity support

### PR DESCRIPTION
**Pull request by rickstaa**
As for my research I mostly use singularity I added a [singularity](https://sylabs.io/docs/) definition file. This container recipe file can be used similar to the docker file. Currently, you still have to build the container locally using the `sudo singularity build universaldatatool.sif Singularity`. If the main maintainer uploads the definition file to the [singularity hub repository](https://singularity-hub.org/about) we can also use the `singularity pull shub://universaldatatool/universaldatatool` and `singularity run universaldatatool/universaldatatool` commands.

### CODE REVIEW

**Review by seveibar — APPROVED** [review]
awesome! looks good! Thanks again @rickstaa!

I haven't used singularity myself but it looks like a great addition!

**Comment by rickstaa** [comment]
@seveibar Great! Thanks again for including singularity into the repository! I was introduced to singularity last year and have to say that I fell in love with the way it handles GPU integration and user permissions. Maybe someone with admin privileges can also add the definition file to the [https://singularity-hub.org](https://singularity-hub.org) repository so we can pull it directly?

**Comment by seveibar** [comment]
Hey @rickstaa, I believe I've done it, I'm guessing the build will be triggered next time we push :)

Here's the link: https://singularity-hub.org/collections/4792

**Comment by rickstaa** [comment]
Great, thanks! I added the collection link to the README.md in #314.

**Pull request merged**
