### PR TITLE
Added whitelist url for reducing error noise on sentry

### PR DESCRIPTION
**Pull request by puskuruk**
We had a lot of local development issues on Sentry and because of that I added whitelist for our Sentry configuration.

### CODE REVIEW

**Comment by seveibar** [comment]
if you do an `npm install`, or change the version of prettier you're using, it's formating with prettier 1.0

**Comment by seveibar** [comment]
then the tests will pass and you won't get a weird extra diff

**Comment by seveibar** [comment]
other than that looks good

**Comment by seveibar** [comment]
need to make sure this logs on desktop (as discussed on slack)

**Comment by puskuruk** [comment]
> need to make sure this logs on desktop (as discussed on slack)

Due to [official docs](https://docs.sentry.io/error-reporting/configuration/?platform=browser#whitelist-urls) added regex.

**Comment by seveibar** [comment]
nice

**Pull request merged**
