### PR TITLE
Fix invalid characters in portuguese translation

### LINKED ISSUE #325: Brazilian portuguese translation has invalid UTF-8 characters
### Issue
When navigating to https://universaldatatool.com/app/ in the portuguese version some of the characters appears like '�'.

### Screenshots
image

### PR DESCRIPTION
**Pull request by miguelcarvalho13**
Closes #325 

### Issue
Some characters were not showing correctly in the brazilian portuguese version.

#### Before
image

#### After
image

### CODE REVIEW

**Comment by miguelcarvalho13** [comment]
It's odd that github diff doesn't show the difference but vscode does:
image

**Comment by seveibar** [comment]
big thanks!!!!

**Comment by seveibar** [comment]
@allcontributors add @miguelcarvalho13 for translations!

**Pull request merged**
